
<html>

<head>
    <meta charset="UTF-8" />
    <title>Menu Example</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="../../app.css" rel="stylesheet" />
</head>


<body>
    <back></back>
    <menu selected="home"></menu>

    <br/>
    <banner n="Home"></banner>

</body>

<script type="module">
    import { menu } from './route.js';
    import { back, banner } from '../../app.js';

    return {};
</script>
</html>